name: "ci-msrv"
on:
  pull_request:
  push:
    branches:
      - master
      - main
  merge_group:
  schedule:
    - cron: '00 06 * * *'
jobs:
  # MSRV check and e2e test
  msrv:
    name: msrv
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build: [ ubuntu, macos, windows ]
        include:
          - build: ubuntu
            os: ubuntu-latest

          - build: macos
            os: macos-latest

          - build: windows
            os: windows-latest
    continue-on-error: true
    steps:
      - name: checkout_repo
        uses: actions/checkout@v4
      - name: install_rust
        uses: dtolnay/rust-toolchain@stable
      - name: workaround_overwrite_cargo_home_for_windows # normally set by dtolnay/rust-toolchain@stable, but always with a forward slash path separator
        if: matrix.build == 'windows'
        run: echo CARGO_HOME=${CARGO_HOME:-$USERPROFILE\\.cargo} >> $GITHUB_ENV
      - name: install_cargo_msrv
        if: matrix.build == 'ubuntu'
        run: cargo install cargo-msrv
      - name: install_cargo_msrv_no_default
        if: matrix.build != 'ubuntu'
        run: cargo install cargo-msrv --no-default-features
      - name: version_of_cargo_msrv
        run: cargo msrv --version
      - name: run_cargo_msrv
        run: cargo msrv --output-format json verify
      - name: run_cargo_msrv_on_verify_failure
        if: ${{ failure() }}
        run: cargo msrv verify --log-target stdout --log-level debug --no-user-output
      - name: debug_run_cargo_msrv
        run: cargo msrv --output-format json verify
      - name: debug_run_cargo_msrv_on_verify_failure
        if: ${{ failure() }}
        run: cargo msrv find --log-target stdout --log-level debug --no-user-output

  # The same as the 'msrv' job, except it takes the latest release, including beta releases
  # We don't use --all-features here!
  msrv_pre_release:
    name: msrv_pre_release
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: checkout_repo
        uses: actions/checkout@v4
      - name: install_rust
        uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall
      - name: install_cargo_msrv_bin
        run: cargo binstall --version 0.16.2 --no-confirm cargo-msrv
      - name: version_of_cargo_msrv
        run: cargo msrv --version
      - name: run_cargo_msrv
        run: cargo msrv --output-format json verify
      - name: run_cargo_msrv_on_verify_failure
        if: ${{ failure() }}
        run: cargo msrv find --output-format json

  # The same as the 'msrv' job, except it takes the latest development branch, as a form of test
  # we don't use --all-features here!
  msrv_development:
    name: msrv_development
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: checkout_repo
        uses: actions/checkout@v4
      - name: install_rust
        uses: dtolnay/rust-toolchain@stable
      - name: install_cargo_msrv
        run: cargo install --git https://github.com/foresterre/cargo-msrv.git cargo-msrv
      - name: version_of_cargo_msrv
        run: cargo msrv --version
      - name: run_cargo_msrv
        run: cargo msrv --output-format json verify
      - name: run_cargo_msrv_on_verify_failure
        if: ${{ failure() }}
        run: cargo msrv find --output-format json
