name: "ci-msrv"
on:
  pull_request:
  push:
    branches:
      - master
      - main
  merge_group:
  schedule:
    - cron: '00 06 * * *'
jobs:
  msrv:
    name: msrv
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: checkout_repo
        uses: actions/checkout@v4
      - name: install_rust
        uses: dtolnay/rust-toolchain@stable
      - name: install_cargo_msrv
        run: cargo install cargo-msrv --all-features
      - name: version_of_cargo_msrv
        run: cargo msrv --version
      - name: run_cargo_msrv
        run: cargo msrv --output-format json verify
      - name: run_cargo_msrv_on_verify_failure
        if: ${{ failure() }}
        run: cargo msrv find --output-format json

  # The same as the 'msrv' job, except it takes the latest release, including beta releases
  # We don't use --all-features here!
  msrv_pre_release:
    name: msrv_pre_release
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: checkout_repo
        uses: actions/checkout@v4
      - name: install_rust
        uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall
      - name: install_cargo_msrv_bin
        run: cargo binstall --version 0.16.0 --no-confirm cargo-msrv
      - name: version_of_cargo_msrv
        run: cargo msrv --version
      - name: run_cargo_msrv
        run: cargo msrv --output-format json verify
      - name: run_cargo_msrv_on_verify_failure
        if: ${{ failure() }}
        run: cargo msrv find --output-format json

  # The same as the 'msrv' job, except it takes the latest development branch, as a form of test
  # we don't use --all-features here!
  msrv_development:
    name: msrv_development
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: checkout_repo
        uses: actions/checkout@v4
      - name: install_rust
        uses: dtolnay/rust-toolchain@stable
      - name: install_cargo_msrv
        run: cargo install --git https://github.com/foresterre/cargo-msrv.git cargo-msrv
      - name: version_of_cargo_msrv
        run: cargo msrv --version
      - name: run_cargo_msrv
        run: cargo msrv --output-format json verify
      - name: run_cargo_msrv_on_verify_failure
        if: ${{ failure() }}
        run: cargo msrv find --output-format json
